version: "3.0"
services:
  postgresql:
   image: performancetesting/aos-postgres:TAG
   ports:
   - "POSTGRES_PORT:5432"
   deploy:
     placement:
       constraints:
         - node.hostname == HOST_NAME
  tomcat_6:
   env_file:
   - .env
   image: performancetesting/aos-main-app:TAG
   ports:
   - "MAIN_PORT:8080"
   deploy:
     placement:
       constraints:
         - node.hostname == HOST_NAME
  tomcat_accountservice:
   env_file:
   - .env
   image: performancetesting/aos-accountservice:TAG
   ports:
   - "ACCOUNT_PORT:8080"
   deploy:
     placement:
       constraints:
         - node.hostname == HOST_NAME
  registry:
   image: registry:2
   ports:
   - "REGISTRY_PORT:5000"
   deploy:
     placement:
       constraints:
         - node.hostname == HOST_NAME
  jenkins:
   env_file:
   - .env	
   image: performancetesting/aos-jenkins-pipline:TAG
   ports:
   - "JENKINS_PORT:8080"
   - "50000:50000"
   volumes:
   - WORKSPACE_ACCOUNT:/var/jenkins_home/jobs/Adventage-Online-Shopping-Pipeline-Commit/workspace
   - WORKSPACE_LEANFT:/var/jenkins_home/jobs/Adventage-Online-Shopping-Build-LEANFT-Jar/workspace
   - /var/run/docker.sock:/var/run/docker.sock
   deploy:
     placement:
       constraints:
         - node.hostname == HOST_NAME
