#spring:
#  application:
#    name: accountservice
#  cloud:
#    config:
#      uri: ${CONFIG_SERVICE_URI}
#      enabled: false
#      fail-fast: true
#    retry:
#      max-attempts: 10000
#      max-interval: 1000