version: '3.0'
services:
  gitlab:
   env_file:
   - .env
   - .env_private
   image: advantageonlineshopping/aos-gitlab:${TAG}
   ports:
   - "${GITLAB_PORT}:80"
   - "443:443"
   - "23:22"
   volumes:
   - '/srv/gitlab/config:/etc/gitlab'
   - '/srv/gitlab/logs:/var/log/gitlab'
   - '/srv/gitlab/data:/var/opt/gitlab'
   container_name: gitlab
   restart: always
  postgresql:
    image: advantageonlineshopping/aos-postgres:${TAG}
    ports:
    - "${POSTGRES_PORT}:5432"
    container_name: postgresql
    restart: always
  tomcat_6:
    env_file:
    - .env
    - .env_private
    image: advantageonlineshopping/aos-main-app:${TAG}
    ports:
    - "${MAIN_PORT}:8080"
    depends_on:
    - "postgresql"
    container_name: tomcat_6
    restart: always
  tomcat_account:
    env_file:
    - .env
    - .env_private
    image: advantageonlineshopping/aos-accountservice:${TAG}
    ports:
    - "${ACCOUNT_PORT}:8080"
    depends_on:
    - "postgresql"
    container_name: tomcat_account
    restart: always
  jenkins:
    env_file:
    - .env
    - .env_private
    image: advantageonlineshopping/aos-jenkins-pipline:${TAG}
    ports:
    - "50000:50000"
    - "${JENKINS_PORT}:8080"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins
    restart: always
  octane:
   env_file:
   - .env
   depends_on:
   - octane_docker_oracle
   - octane_es
   ports:
   - ${OCTANE_PORT}:8080
   - 5701
   networks:
     octanet:
       aliases:
       - octane1
   environment:
     SCHEMA_NAME: 'octane_sa'
     SCHEMA_PASSWORD: 'tdtdtd'
     DB_ACTION: 'CREATE_NEW'
     DB_SERVER_NAME: 'octane_docker_oracle'
     DB_SERVER_PORT: '1521'
     SERVICE_NAME: 'xe'
     DB_ADMIN_USER: 'system'
     DB_ADMIN_PASSWORD: 'oracle'
     TABLE_SPACE: 'USERS'
     TEMP_TABLE_SPACE: 'TEMP'
     DB_PROTOCOL: 'jdbc:mercury:oracle'
     DISABLE_VALIDATOR_MEMORY: 'true'
     NGA_HEAP_SIZE: '1024'
     ELASTIC_HOST: 'octane_es'
     ELASTIC_PORT: '9300'
     ELASTIC_CLUSTER_NAME: 'elasticsearch'
     SERVER_DOMAIN: 'hpeswlab.net'
     MQM_URL: ''
     SITEADMINISTRATOR_USER: 'sa@nga'
     ADMIN_PASSWORD: 'Welcome1'
     REPOSITORY_FOLDER: '/opt/octane/repo'
     INIT_STRING: 'InitString'
     AUTH_TOKEN_ENCRYPTION_KEY: 'AuthToken'
     DISTRIBUTED_UUID: 'DistributedPass'
     INSTALLATION_FOLDER: '/opt/octane/install'
     WAR_FOLDER: '/opt/octane/webapps/root'
     DEBUG: 'true'
     ENABLE_SERVICES_INTEGRATION: 'true'
     APP_URL: 'http://${OCTANE_IP}:${OCTANE_PORT}'
   tty: true
   image: ${IMAGE}
   stdin_open: true
  octane_docker_oracle:
    networks:
      octanet:
        aliases:
        - octane_docker_oracle
    tty: true
    image: alexeiled/docker-oracle-xe-11g
    stdin_open: true
    ports:
    - 1521
  octane_es:
    networks:
      octanet:
        aliases:
        - octane_es
    environment:
      ES_HEAP_SIZE: 4G
    tty: true
    image: elasticsearch:2.4
    ports:
    - 9300
    - 9200
    stdin_open: true
networks:
  octanet:
    driver: bridge