

package com.advantage.accountrest.AccountserviceClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 *
 */
@WebServiceClient(name = "AccountServicePortService", targetNamespace = "com.advantage.online.store.accountservice", wsdlLocation = "http://localhost:8081/ws/accountservice.wsdl")
public class AccountServicePortService
        extends Service
{

    private final static URL ACCOUNTSERVICEPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTSERVICEPORTSERVICE_EXCEPTION;
    private final static QName ACCOUNTSERVICEPORTSERVICE_QNAME = new QName("com.advantage.online.store.accountservice", "AccountServicePortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ws/accountservice.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTSERVICEPORTSERVICE_WSDL_LOCATION = url;
        ACCOUNTSERVICEPORTSERVICE_EXCEPTION = e;
    }

    public AccountServicePortService() {
        super(__getWsdlLocation(), ACCOUNTSERVICEPORTSERVICE_QNAME);
    }

    public AccountServicePortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTSERVICEPORTSERVICE_QNAME, features);
    }

    public AccountServicePortService(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTSERVICEPORTSERVICE_QNAME);
    }

    public AccountServicePortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTSERVICEPORTSERVICE_QNAME, features);
    }

    public AccountServicePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountServicePortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AccountServicePort
     */
    @WebEndpoint(name = "AccountServicePortSoap11")
    public AccountServicePort getAccountServicePortSoap11() {
        return super.getPort(new QName("com.advantage.online.store.accountservice", "AccountServicePortSoap11"), AccountServicePort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountServicePort
     */
    @WebEndpoint(name = "AccountServicePortSoap11")
    public AccountServicePort getAccountServicePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("com.advantage.online.store.accountservice", "AccountServicePortSoap11"), AccountServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTSERVICEPORTSERVICE_EXCEPTION!= null) {
            throw ACCOUNTSERVICEPORTSERVICE_EXCEPTION;
        }
        return ACCOUNTSERVICEPORTSERVICE_WSDL_LOCATION;
    }

}
