
package com.advantage.accountrest.AccountserviceClient;

import accountservice.store.online.advantage.com.AccountStatusRequest;
import com.advantage.accountsoap.dto.account.*;
import com.advantage.accountsoap.dto.account.AccountCreateResponse;
import com.advantage.accountsoap.dto.account.AccountDeleteResponse;
import com.advantage.accountsoap.dto.account.AccountLogoutResponse;
import com.advantage.accountsoap.dto.account.AccountPermanentDeleteResponse;
import com.advantage.accountsoap.dto.account.ChangePasswordResponse;
import com.advantage.accountsoap.dto.address.*;
import com.advantage.accountsoap.dto.country.*;
import com.advantage.accountsoap.dto.payment.*;


import javax.jws.*;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 *
 */
@WebService(name = "AccountServicePort", targetNamespace = "com.advantage.online.store.accountservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface AccountServicePort {


    /**
     *
     * @param getAccountByIdRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.GetAccountByIdResponse
     */
    @WebMethod(operationName = "GetAccountById")
    @WebResult(name = "GetAccountByIdResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountByIdResponse")
    public GetAccountByIdResponse getAccountById(
            @WebParam(name = "GetAccountByIdRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountByIdRequest")
                    GetAccountByIdRequest getAccountByIdRequest);

    /**
     *
     * @param accountDeleteRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.AccountDeleteResponse
     */
    @WebMethod(operationName = "AccountDelete")
    @WebResult(name = "AccountDeleteResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountDeleteResponse")
    public AccountDeleteResponse accountDelete(
            @WebParam(name = "AccountDeleteRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountDeleteRequest")
                    AccountDeleteRequest accountDeleteRequest);

    /**
     *
     * @param addressUpdateRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.AddressUpdateResponse
     */
    @WebMethod(operationName = "AddressUpdate")
    @WebResult(name = "AddressUpdateResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AddressUpdateResponse")
    public AddressUpdateResponse addressUpdate(
            @WebParam(name = "AddressUpdateRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AddressUpdateRequest")
                    AddressUpdateRequest addressUpdateRequest);

    /**
     *
     * @param getAllAccountsRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.GetAllAccountsResponse
     */
    @WebMethod(operationName = "GetAllAccounts")
    @WebResult(name = "GetAllAccountsResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAllAccountsResponse")
    public GetAllAccountsResponse getAllAccounts(
            @WebParam(name = "GetAllAccountsRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAllAccountsRequest")
                    GetAllAccountsRequest getAllAccountsRequest);

    /**
     *
     * @param addSafePayMethodRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.AddSafePayMethodResponse
     */
    @WebMethod(operationName = "AddSafePayMethod")
    @WebResult(name = "AddSafePayMethodResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AddSafePayMethodResponse")
    public AddSafePayMethodResponse addSafePayMethod(
            @WebParam(name = "AddSafePayMethodRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AddSafePayMethodRequest")
                    AddSafePayMethodRequest addSafePayMethodRequest);

    /**
     *
     * @param updateSafePayMethodRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.UpdateSafePayMethodResponse
     */
    @WebMethod(operationName = "UpdateSafePayMethod")
    @WebResult(name = "UpdateSafePayMethodResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "UpdateSafePayMethodResponse")
    public UpdateSafePayMethodResponse updateSafePayMethod(
            @WebParam(name = "UpdateSafePayMethodRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "UpdateSafePayMethodRequest")
                    UpdateSafePayMethodRequest updateSafePayMethodRequest);

    /**
     *
     * @param getAccountFieldsRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.GetAccountFieldsResponse
     */
    @WebMethod(operationName = "GetAccountFields")
    @WebResult(name = "GetAccountFieldsResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountFieldsResponse")
    public GetAccountFieldsResponse getAccountFields(
            @WebParam(name = "GetAccountFieldsRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountFieldsRequest")
                    GetAccountFieldsRequest getAccountFieldsRequest);

    /**
     *
     * @param countrySearchRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.CountrySearchResponse
     */
    @WebMethod(operationName = "CountrySearch")
    @WebResult(name = "CountrySearchResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "CountrySearchResponse")
    public CountrySearchResponse countrySearch(
            @WebParam(name = "CountrySearchRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "CountrySearchRequest")
                    CountrySearchRequest countrySearchRequest);

    /**
     *
     * @param getAccountConfigurationRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.GetAccountConfigurationResponse
     */
    @WebMethod(operationName = "GetAccountConfiguration")
    @WebResult(name = "GetAccountConfigurationResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountConfigurationResponse")
    public GetAccountConfigurationResponse getAccountConfiguration(
            @WebParam(name = "GetAccountConfigurationRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountConfigurationRequest")
                    GetAccountConfigurationRequest getAccountConfigurationRequest);

    /**
     *
     * @param paymentPreferencesStatusRequest
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "PaymentPreferencesStatus")
    @WebResult(name = "PaymentPreferencesStatusResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "PaymentPreferencesStatusResponse")
    public Object paymentPreferencesStatus(
            @WebParam(name = "PaymentPreferencesStatusRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "PaymentPreferencesStatusRequest")
                    Object paymentPreferencesStatusRequest);

    /**
     *
     * @param addressStatusRequest
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "AddressStatus")
    @WebResult(name = "AddressStatusResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AddressStatusResponse")
    public Object addressStatus(
            @WebParam(name = "AddressStatusRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AddressStatusRequest")
                    Object addressStatusRequest);

    /**
     *
     * @param updateMasterCreditMethodRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.UpdateMasterCreditMethodResponse
     */
    @WebMethod(operationName = "UpdateMasterCreditMethod")
    @WebResult(name = "UpdateMasterCreditMethodResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "UpdateMasterCreditMethodResponse")
    public UpdateMasterCreditMethodResponse updateMasterCreditMethod(
            @WebParam(name = "UpdateMasterCreditMethodRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "UpdateMasterCreditMethodRequest")
                    UpdateMasterCreditMethodRequest updateMasterCreditMethodRequest);

    /**
     *
     * @param accountCreateRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.AccountCreateResponse
     */
    @WebMethod(operationName = "AccountCreate")
    @WebResult(name = "AccountCreateResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountCreateResponse")
    public AccountCreateResponse accountCreate(
            @WebParam(name = "AccountCreateRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountCreateRequest")
                    AccountCreateRequest accountCreateRequest);

    /**
     *
     * @param accountLogoutRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.AccountLogoutResponse
     */
    @WebMethod(operationName = "AccountLogout")
    @WebResult(name = "AccountLogoutResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountLogoutResponse")
    public AccountLogoutResponse accountLogout(
            @WebParam(name = "AccountLogoutRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountLogoutRequest")
                    AccountLogoutRequest accountLogoutRequest);

    /**
     *
     * @param addMasterCreditMethodRequest
     */
    @WebMethod(operationName = "AddMasterCreditMethod")
    @Oneway
    public void addMasterCreditMethod(
            @WebParam(name = "AddMasterCreditMethodRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AddMasterCreditMethodRequest")
                    AddMasterCreditMethodRequest addMasterCreditMethodRequest);

    /**
     *
     * @param getAccountByIdNewRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.GetAccountByIdNewResponse
     */
    @WebMethod(operationName = "GetAccountByIdNew")
    @WebResult(name = "GetAccountByIdNewResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountByIdNewResponse")
    public GetAccountByIdNewResponse getAccountByIdNew(
            @WebParam(name = "GetAccountByIdNewRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountByIdNewRequest")
                    GetAccountByIdNewRequest getAccountByIdNewRequest);

    /**
     *
     * @param accountUpdateRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.AccountUpdateResponse
     */
    @WebMethod(operationName = "AccountUpdate")
    @WebResult(name = "AccountUpdateResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountUpdateResponse")
    public AccountUpdateResponse accountUpdate(
            @WebParam(name = "AccountUpdateRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountUpdateRequest")
                    AccountUpdateRequest accountUpdateRequest);

    /**
     *
     * @param changePasswordRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.ChangePasswordResponse
     */
    @WebMethod(operationName = "ChangePassword")
    @WebResult(name = "ChangePasswordResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "ChangePasswordResponse")
    public ChangePasswordResponse changePassword(
            @WebParam(name = "ChangePasswordRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "ChangePasswordRequest")
                    ChangePasswordRequest changePasswordRequest);

    /**
     *
     * @param accountLoginRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.AccountLoginResponse
     */
    @WebMethod(operationName = "AccountLogin")
    @WebResult(name = "AccountLoginResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountLoginResponse")
    public AccountLoginResponse accountLogin(
            @WebParam(name = "AccountLoginRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountLoginRequest")
                    AccountLoginRequest accountLoginRequest);

    /**
     *
     * @param accountPermanentDeleteRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.AccountPermanentDeleteResponse
     */
    @WebMethod(operationName = "AccountPermanentDelete")
    @WebResult(name = "AccountPermanentDeleteResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountPermanentDeleteResponse")
    public AccountPermanentDeleteResponse accountPermanentDelete(
            @WebParam(name = "AccountPermanentDeleteRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountPermanentDeleteRequest")
                    AccountPermanentDeleteRequest accountPermanentDeleteRequest);

    /**
     *
     * @param accountStatusRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.AccountStatusResponse
     */
    @WebMethod(operationName = "AccountStatus")
    @WebResult(name = "AccountStatusResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountStatusResponse")
    public AccountStatusResponse accountStatus(
            @WebParam(name = "AccountStatusRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AccountStatusRequest")
                    AccountStatusRequest accountStatusRequest);

    /**
     *
     * @param paymentMethodUpdateRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.PaymentMethodUpdateResponse
     */
    @WebMethod(operationName = "PaymentMethodUpdate")
    @WebResult(name = "PaymentMethodUpdateResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "PaymentMethodUpdateResponse")
    public PaymentMethodUpdateResponse paymentMethodUpdate(
            @WebParam(name = "PaymentMethodUpdateRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "PaymentMethodUpdateRequest")
                    PaymentMethodUpdateRequest paymentMethodUpdateRequest);

    /**
     *
     * @param getAccountPaymentPreferencesRequest
     */
    @WebMethod(operationName = "GetAccountPaymentPreferences")
    @Oneway
    public void getAccountPaymentPreferences(
            @WebParam(name = "GetAccountPaymentPreferencesRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAccountPaymentPreferencesRequest")
                    GetAccountPaymentPreferencesRequest getAccountPaymentPreferencesRequest);

    /**
     *
     * @param restoreDBToFactorySettingRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.RestoreDBToFactorySettingResponse
     */
    @WebMethod(operationName = "RestoreDBToFactorySetting")
    @WebResult(name = "RestoreDBToFactorySettingResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "RestoreDBToFactorySettingResponse")
    public RestoreDBToFactorySettingResponse restoreDBToFactorySetting(
            @WebParam(name = "RestoreDBToFactorySettingRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "RestoreDBToFactorySettingRequest")
                    RestoreDBToFactorySettingRequest restoreDBToFactorySettingRequest);

    /**
     *
     * @param getAddressesByAccountIdRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.GetAddressesByAccountIdResponse
     */
    @WebMethod(operationName = "GetAddressesByAccountId")
    @WebResult(name = "GetAddressesByAccountIdResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAddressesByAccountIdResponse")
    public GetAddressesByAccountIdResponse getAddressesByAccountId(
            @WebParam(name = "GetAddressesByAccountIdRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetAddressesByAccountIdRequest")
                    GetAddressesByAccountIdRequest getAddressesByAccountIdRequest);

    /**
     *
     * @param countryCreateRequest
     */
    @WebMethod(operationName = "CountryCreate")
    @Oneway
    public void countryCreate(
            @WebParam(name = "CountryCreateRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "CountryCreateRequest")
                    CountryCreateRequest countryCreateRequest);

    /**
     *
     * @param getCountriesRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.GetCountriesResponse
     */
    @WebMethod(operationName = "GetCountries")
    @WebResult(name = "GetCountriesResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetCountriesResponse")
    public GetCountriesResponse getCountries(
            @WebParam(name = "GetCountriesRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "GetCountriesRequest")
                    Object getCountriesRequest);

    /**
     *
     * @param deletePaymentPreferenceRequest
     * @return
     *     returns https.www_advantageonlineshopping_com.ws.DeletePaymentPreferenceResponse
     */
    @WebMethod(operationName = "DeletePaymentPreference")
    @WebResult(name = "DeletePaymentPreferenceResponse", targetNamespace = "com.advantage.online.store.accountservice", partName = "DeletePaymentPreferenceResponse")
    public DeletePaymentPreferenceResponse deletePaymentPreference(
            @WebParam(name = "DeletePaymentPreferenceRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "DeletePaymentPreferenceRequest")
                    DeletePaymentPreferenceRequest deletePaymentPreferenceRequest);

    /**
     *
     * @param addAddressesRequest
     */
    @WebMethod(operationName = "AddAddresses")
    @Oneway
    public void addAddresses(
            @WebParam(name = "AddAddressesRequest", targetNamespace = "com.advantage.online.store.accountservice", partName = "AddAddressesRequest")
                    AddAddressesRequest addAddressesRequest);

}
